easy_admin:
  design:
    form_theme:
      - "@EasyAdmin/form/bootstrap_4.html.twig"
      - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
  entities:
    Product:
      # ...
      form:
        fields:
          # ...
          - { property: "description", type: "fos_ckeditor" }
