# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

# twig:
#   form_themes:
#     - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
# fos_ck_editor:
#   input_sync: true
#   default_config: base_config
#   configs:
#     base_config:
#       toolbar: full
#   base_path: "build/ckeditor"
#   js_path: "build/ckeditor/ckeditor.js"

fos_ck_editor:
  default_config: my_config
  input_sync: true
  base_path: "build/ckeditor"
  js_path: "build/ckeditor/ckeditor.js"
  configs:
    my_config:
      contentsLanguage: fr
      toolbar: full
      # filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: []
twig:
  form_themes:
    - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
