vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: build/images/thumbnails
            upload_destination: '%kernel.project_dir%/public/build/images/thumbnails'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        marque_images:
            uri_prefix: build/images/marques
            upload_destination: '%kernel.project_dir%/public/build/images/marques'
            namer: Vich\UploaderBundle\Naming\UniqidNamer