vich_uploader:
  db_driver: orm

  mappings:
    posters:
      uri_prefix: "assets/images/posters"
      upload_destination: "%kernel.project_dir%/assets/images/posters"
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    marque_images:
      uri_prefix: "assets/images/marques"
      upload_destination: "%kernel.project_dir%/assets/images/marques"
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    camera_images:
      uri_prefix: "assets/images/imagesCam"
      upload_destination: "%kernel.project_dir%/assets/images/imagesCam"
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    thumbnails:
      uri_prefix: "assets/images/thumbnails"
      upload_destination: "%kernel.project_dir%/assets/images/thumbnails"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
