vich_uploader:
    db_driver: orm

    mappings:
        posters:
            uri_prefix: build/images/posters
            upload_destination: '%kernel.project_dir%/public/build/images/posters'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        marque_images:
            uri_prefix: build/images/marques
            upload_destination: '%kernel.project_dir%/public/build/images/marques'
            namer: Vich\UploaderBundle\Naming\UniqidNamer