monolog:
  channels:
    - honey_pot
  handlers:
    honeypot:
      level: info
      type: rotating_file
      max_files: 10
      path: "%kernel.logs_dir%/security/honeypot/honeypot.%kernel.environment%.log"
      channels:
        - app
        - honey_pot

    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
    # uncomment to get logging in your browser
    # you may have to allow bigger header sizes in your Web server configuration
    #firephp:
    #    type: firephp
    #    level: info
    #chromephp:
    #    type: chromephp
    #    level: info
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]
